cat << 'EOF' > .github/workflows/gitops.yml
name: "Terragrunt Local GitOps"

on:
  push:
    branches: [ "main" ]

jobs:
  dev-env:
    name: "Deploy Dev"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terragrunt Apply Dev
        run: |
          cd live/dev
          terragrunt apply -auto-approve --terragrunt-non-interactive

  prod-env:
    name: "Deploy Prod"
    runs-on: self-hosted
    needs: dev-env
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terragrunt Apply Prod
        run: |
          cd live/prod
          terragrunt apply -auto-approve --terragrunt-non-interactive
EOF
