name: Terragrunt Local GitOps

on:
  push:
    branches:
      - main

env:
  TF_IN_AUTOMATION: "true"

jobs:
  dev-env:
    name: Deploy Dev
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clean Old Dev Containers
        run: |
          docker rm -f $(docker ps -a -q --filter "name=^dev-") 2>/dev/null || true

#      - name: Terragrunt Apply Dev
#        run: |
#          cd live/dev
#          terragrunt apply -auto-approve

      - name: Clear Terragrunt Cache Dev
        run: |
          rm -rf live/dev/k3s-monitoring/.terragrunt-cache
          rm -rf live/dev/k3s-vault/.terragrunt-cache

      - name: Terragrunt Apply Dev Monitoring
        run: |
          cd live/dev/k3s-monitoring
          terragrunt apply -auto-approve

      - name: Terragrunt Apply dev Vault
        run: |
          cd live/dev/k3s-vault
          terragrunt apply -auto-approve 

  prod-env:
    name: Deploy Prod
    runs-on: self-hosted
    needs: dev-env
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clean Old Prod Containers
        run: |
          docker rm -f $(docker ps -a -q --filter "name=^prod-") 2>/dev/null || true

      - name: Clear Terragrunt Cache Prod
        run: |
          rm -rf live/prod/k3s-monitoring/.terragrunt-cache
          rm -rf live/prod/k3s-vault/.terragrunt-cache

#      - name: Terragrunt Apply Prod
#        run: |
#          cd live/prod
#          terragrunt apply -auto-approve

      - name: Terragrunt Apply Prod Monitoring
        run: |
          cd live/prod/k3s-monitoring
          terragrunt apply -auto-approve

      - name: Terragrunt Apply Prod Vault
        run: |
          cd live/prod/k3s-vault
          terragrunt apply -auto-approve      